name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_release:
    name: check spelling
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        submodules: recursive
      
    - uses: actions/setup-go@v4
    - run: curl -L https://git.io/misspell | bash

    - name: Check spelling
      run: ./bin/misspell -error ./src/app/**